---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: debian-7.7
  - name: centos-6.5


suites:
  - name: default
    run_list:
      - recipe[simple-mailcatcher-test]
    attributes:

